apiVersion: v1
kind: Pod
metadata:
  name: mount-test
  labels:
    name: mount-test
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: nginx-http-port
          containerPort: 80
      volumeMounts:
        - name: docroot
          mountPath: /usr/share/nginx/html
          readOnly: false
  volumes:
    - name: docroot
      hostPath:
        path: /path # absolute path
