apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: localhost:5000/go-api:latest
        ports:
        - containerPort: 1234
---
kind: Service
apiVersion: v1
metadata:
  name: go-api-svc
spec:
  selector:
    app: go-api
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 1234
