version: "3"
services:
  backapi:
    build: ./backapi
    image: wararaki/sample-fastapi:2.0
    ports:
      - "8000:8000"
    networks: 
      - fast_net
  frontapi:
    build: ./frontapi
    image: wararaki/sample-fastapi2:1.1
    ports:
      - "8001:8001"
    networks: 
      - fast_net

networks: 
  fast_net:
    external: true
